server:
  address: localhost
  port: 11000
spring:
  devtools:
    restart:
      enabled: true
  profiles:
    group:
      dev: dev
      prod:

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: "jdbc:postgresql://holme-db.ceup2aplufna.eu-north-1.rds.amazonaws.com:5432/postgres?schema=public"
    username: postgres
    password: q1w2e3r4!!
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true